version: '3.0'

services:
  grafana:
    container_name: 'basic-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.1.2}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3000:3000/tcp
      - 2345:2345
    command: --config /var/lib/grafana/config.ini
    volumes:
      - ./:/var/lib/grafana/plugins/eficacia-datatable-backend
      - ./provisioning:/etc/grafana/provisioning
      - ./.config/config.ini:/var/lib/grafana/config.ini
